steps:
  # Step 1: Install dependencies
  - name: 'python:3.9'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']

  # Step 2: Run linting (optional)
  - name: 'python:3.9'
    entrypoint: pylint
    args: ['src']

  # Step 3: Run unit tests
  - name: 'python:3.9'
    entrypoint: pytest
    args: ['test']


  - name: 'python:3.9'
    entrypoint: bash
    args:
      - '-c'
      - |
        python src/main.py &
        sleep 5  # Wait for the app to start
        pytest test/integration  # Run integration tests

  # Step 5: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA', '.']

  # Step 6: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA']

# Images to push to Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA'

# Timeout for the entire build (optional)
timeout: '1800s'

