steps:
  # Step 1: Install dependencies
  - name: 'python:3.11-slim'
    entrypoint: pip
    args: ['install', '-r', 'requirements-dev.txt']

  # Step 2: # ToDo add pre-commit hooks


  # Step 3: Run unit tests
  - name: 'python:3.9'
    entrypoint: pytest
    args: ['tests']

  # Step 4: Run integration tests
  - name: 'python:3.9'
    entrypoint: bash
    args:
      - '-c'
      - |
        uvicorn src.main:app --host 0.0.0.0 --port 8080 &
        sleep 5  # Wait for the app to start

  # Step 5: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA', '.']

  # Step 6: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA']

# Images to push to Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/fastapi-app:$COMMIT_SHA'

# Timeout for the entire build (optional)
timeout: '1800s'